version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "daily"
      time: "04:41"
      timezone: "Asia/Tokyo"
  - package-ecosystem: "pip"
    directory: "/backend/src"
    schedule:
      interval: "daily"
      time: "04:41"
      timezone: "Asia/Tokyo"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "04:41"
      timezone: "Asia/Tokyo"
