services:
  nginx-proxy:
    image: ghcr.io/programminglab/backend-nginx:develop
    restart: always
    network_mode: "host"
    depends_on:
      - flask-app
#    command: /app/start.sh
  flask-app:
    image: ghcr.io/programminglab/backend-flask:develop
    restart: always
    network_mode: "host"
    command: gunicorn -w 3 -t 60 app:app