services:
  nginx-proxy:
    build: nginx
    image: ghcr.io/ProgrammingLab/backend-nginx:main
    restart: always
    network_mode: "host"
    depends_on:
      - flask-app
    command: /app/start.sh
  flask-app:
    build: flask
    image: ghcr.io/ProgrammingLab/backend-flask:main
    restart: always
    network_mode: "host"